name: Release with commit

on:
  push:
    branches:
      - stable
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.3.0
        with:
          regexp: "Version ((\\d+(?:\\.\\d+)*)(-(?:alpha|beta|rc)\\d*(?:(?:\\s|\\S)*))?)"
          regexp_options: "us"
          release_name: "Version $1"
          tag_name: "v$1"
          body: ""
          draft: false
          prerelease: false
        env:
          GITHUB_USER: "${{secrets.GITHUB_USER}}"
          GITHUB_TOKEN: "${{secrets.PAT}}"
